# Generated by Django 4.2.24 on 2025-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelrecord',
            name='owned_products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
