# Generated by Django 4.2.24 on 2025-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0002_alter_panelrecord_owned_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelrecord',
            name='brand_smoked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='brand_smoked_ETC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='car_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='ever_alcohol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='ever_esmoked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='ever_smoked_ETC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='ever_smoked_brand_ETC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='p_company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
