# Generated by Django 4.2.24 on 2025-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0003_alter_panelrecord_brand_smoked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelrecord',
            name='car_ownship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='famsize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='h_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='married',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='p_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
