# Generated by Django 4.2.24 on 2025-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdb', '0004_alter_panelrecord_car_ownship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelrecord',
            name='car_manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='car_ownship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='education_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='ever_smoked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='ever_smoked_brand_ETC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='famsize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='h_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='married',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='p_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='p_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='phone_brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='phone_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecord',
            name='subregion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
