# Generated by Django 4.2.24 on 2025-11-02 11:47

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_update_itemembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocVec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('vec', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
        ),
        migrations.RenameIndex(
            model_name='itemembedding',
            new_name='kure_item_e_uid_7a1ee2_idx',
            old_name='idx_uid_sub',
        ),
        migrations.RenameIndex(
            model_name='itemembedding',
            new_name='kure_item_e_uid_7a1ee2_idx',
            old_name='idx_uid_sub',
        ),
    ]
