# Generated by Django 4.2.24 on 2025-11-02 13:39

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_docvec_rename_idx_uid_sub_kure_item_e_uid_7a1ee2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemembedding',
            name='vec',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
